rebot:
  image: sciquest/hubot
  hostname: hubot
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "8080:8080"
  environment:
  - OWNER=hubot
  - HUBOT_NAME=JARVIS
  - DESCRIPTION=Im a robot.. with freaking laser beams....
  - ADAPTER_NAME=hipchat
  - SLACK_ADAPTER_TOKEN=''
  - SLACK_TEAM=''
  - SLACK_BOT_NAME=''
  - GTALK_API_KEY=''
  - HUBOT_HIPCHAT_TOKEN=0f743d5078132aebb0d2252886d0fa
  - HUBOT_HIPCHAT_JID=83124_3305361@chat.hipchat.com
  - HUBOT_HIPCHAT_NAME=jarvis
  - HUBOT_HIPCHAT_PASSWORD=5F&0P7^e930E
  - HUBOT_HIPCHAT_ROOMS=''
  - WHITELIST_DOMAINS=''
  - TERMTAG=JARVIS
  command: /bin/bash