robot:
  image: appcontainers/hubot
  hostname: hubot
  mem_limit: 2048m
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "8080:8080"
  environment:
  - OWNER=hubot
  - HUBOT_NAME=HUBOT
  - DESCRIPTION=Im a chat robot....
  - ADAPTER_NAME=<hipchat|slack|gtalk>
  - SLACK_ADAPTER_TOKEN=''
  - SLACK_TEAM=''
  - SLACK_BOT_NAME=''
  - GTALK_API_KEY=''
  - HUBOT_HIPCHAT_TOKEN=''
  - HUBOT_HIPCHAT_JID=''
  - HUBOT_HIPCHAT_NAME=hubot
  - HUBOT_HIPCHAT_PASSWORD=''
  - HUBOT_HIPCHAT_ROOMS=''
  - WHITELIST_DOMAINS=''
  - TERMTAG=JARVIS
  - HUBOT_JENKINS_URL=http://jenkins.yourcompany.com:8080
  - HUBOT_JENKINS_AUTH=hubot:hubotpassword
  - HUBOT_GITLAB_URL=http://gitlab.yourcompany.com
  - HUBOT_GITLAB_ACCESSKEY=<Key From Gitlab>
  command: /bin/bash
